<?php

namespace ContainerOg9gdVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Controller\SessionController' shared autowired service.
     *
     * @return \App\Controller\SessionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SessionController.php';

        return $container->privates['App\\Controller\\SessionController'] = new \App\Controller\SessionController(($container->services['.container.private.session'] ?? $container->load('get_Container_Private_SessionService')));
    }
}
