#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register_form:
  path: /register_form
  controller: App\Controller\UserController::registerForm
register_user:
  path: /register_user
  methods: GET
  controller: App\Controller\UserController::registerUser 
login_form:
  path: /login_form
  controller: App\Controller\SecurityController::logInForm
login_user:
  path: /login_user
  methods: GET
  controller: App\Controller\UserController::logInUser  
start_lobby_page:
  path: /start_lobby_page/{userId}
  methods: GET
  controller: App\Controller\UserController::startLobbyPage

main_game:
  path: /main_game
  controller: App\Controller\UserController::mainGame

