#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register_form:
  path: /register_form
  controller: App\Controller\UserController::registerForm
register_user:
  path: /register_user
  methods: GET
  controller: App\Controller\UserController::registerUser 
login_form:
  path: /login_form
  controller: App\Controller\UserController::logInForm
login_user:
  path: /login_user
  methods: GET
  controller: App\Controller\UserController::logInUser  
logout:
  path: /logout
  controller: App\Controller\UserController::logout  
find_username:
  path: /find_username
  controller: App\Controller\UserController::findUsername    

start_lobby_page:
  path: /start_lobby_page
  controller: App\Controller\LobbyPlaceController::startLobbyPage
create_lobby:
  path: /create_lobby
  controller: App\Controller\LobbyPlaceController::createLobby  
join_lobby:
  path: /join_lobby
  controller: App\Controller\LobbyPlaceController::joinLobby
find_key_room:
  path: /find_key_room
  methods: GET
  controller: App\Controller\LobbyPlaceController::findKeyRoom  
get_color_flag:
  path: /get_color_flag
  methods: GET
  controller: App\Controller\LobbyPlaceController::getPlayerColorFlag
lobby_page:
  path: /lobby_page/{keyRoom}
  methods: GET
  controller: App\Controller\LobbyPlaceController::lobbyPage    
quit_lobby:
  path: /quit_lobby
  controller: App\Controller\LobbyPlaceController::quitFromLobby
kick_from_lobby:
  path: /kick_from_lobby
  methods: POST
  controller: App\Controller\LobbyPlaceController::kickFromLobby  
make_guest_host:
  path: /make_guest_host
  methods: POST
  controller: App\Controller\LobbyPlaceController::makeGuestHost
make_player_ready:
  path: /make_player_ready
  methods: POST
  controller: App\Controller\LobbyPlaceController::makePlayerReady
make_player_not_ready:
  path: /make_player_not_ready
  methods: POST
  controller: App\Controller\LobbyPlaceController::makePlayerNotReady 
get_player_status:
  path: /get_player_status
  methods: POST
  controller: App\Controller\LobbyPlaceController::getPlayerStatus  
find_count_players:
  path: /find_count_players
  methods: POST
  controller: App\Controller\LobbyPlaceController::findCountPLayersInLobby
is_all_players_ready:
  path: /is_all_players_ready
  methods: POST
  controller: App\Controller\LobbyPlaceController::isAllPlayersReady
is_host_exist:
  path: /is_host_exist
  methods: POST
  controller: App\Controller\LobbyPlaceController::isHostExist
get_ids_players:
  path: /get_player_ids
  methods: POST
  controller: App\Controller\LobbyPlaceController::getPlayersIdsInLobby
make_players_not_ready:
  path: /make_players_not_ready
  methods: POST
  controller: App\Controller\LobbyPlaceController::makePlayersNotReady

main_game:
  path: /main_game/{keyRoom}
  controller: App\Controller\GameController::mainGame  
start_game:
  path: /start_game
  methods: POST
  controller: App\Controller\GameController::startGame
add_user_to_game:
  path: /add_user_to_game
  methods: POST
  controller: App\Controller\GameController::addUserToGame
create_map: 
  path: /create_map
  methods: POST
  controller: App\Controller\GameController::createGameMap
find_map:
  path: /find_map
  methods: POST
  controller: App\Controller\GameController::findGameMap
update_map:
  path: /update_map
  methods: GET
  controller: App\Controller\GameController::updateGameMap
end_game: 
  path: /end_game
  controller: App\Controller\GameController::endGame
set_game_status:
  path: /set_game_status
  methods: POST
  controller: App\Controller\GameController::setGameStatus
get_game_status:
  path: /get_game_status
  methods: GET
  controller: App\Controller\GameController::getGameStatus

create_build:
  path: /create_build
  methods: POST
  controller: App\Controller\IslandBuildController::createIslandBuild
view_all_builds:
  path: /view_all_builds
  methods: GET
  controller: App\Controller\IslandBuildController::viewAllBuilds
set_hp_to_build:
  path: /set_hp_to_build
  methods: POST
  controller: App\Controller\IslandBuildController::setNewHpToBuild
set_illness_to_build:
  path: /set_illness_to_build
  methods: POST
  controller: App\Controller\IslandBuildController::setIllnessToBuild
unset_illness_to_build:
  path: /unset_illness_to_build
  methods: POST
  controller: App\Controller\IslandBuildController::unsetIllnessToBuild
delete_build:
  path: /delete_build
  methods: POST
  controller: App\Controller\IslandBuildController::deleteBuild
delete_builds_in_game:
  path: /delete_builds_in_game
  controller: App\Controller\IslandBuildController::deleteBuildsInGame

create_island:
  path: /create_island  
  controller: App\Controller\IslandController::createIsland
view_island:
  path: /view_island
  methods: GET
  controller: App\Controller\IslandController::viewIsland
update_island:
  path: /update_island
  methods: POST
  controller: App\Controller\IslandController::updateIsland
view_islands_in_game:
  path: /view_islands_in_game
  methods: POST
  controller: App\Controller\IslandController::viewIslandsInGame

error_page:
  path: /error_page/{messageCode}
  methods: GET
  controller: App\Controller\ErrorController::onError