#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register_form:
  path: /register_form
  controller: App\Controller\UserController::registerForm
register_user:
  path: /register_user
  methods: GET
  controller: App\Controller\UserController::registerUser 
login_form:
  path: /login_form
  controller: App\Controller\UserController::logInForm
login_user:
  path: /login_user
  methods: GET
  controller: App\Controller\UserController::logInUser  
logout:
  path: /logout
  controller: App\Controller\UserController::logout  
start_lobby_page:
  path: /start_lobby_page
  controller: App\Controller\UserController::startLobbyPage
join_lobby:
  path: /join_lobby
  controller: App\Controller\UserController::joinLobby
lobby_page:
  path: /lobby_page
  controller: App\Controller\UserController::lobbyPage    

main_game:
  path: /main_game
  controller: App\Controller\UserController::mainGame