<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOg9gdVS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOg9gdVS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOg9gdVS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOg9gdVS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOg9gdVS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Og9gdVS',
    'container.build_id' => 'b0051345',
    'container.build_time' => 1720433803,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOg9gdVS');
