<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOv1aVJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOv1aVJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOv1aVJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOv1aVJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOOv1aVJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OOv1aVJ',
    'container.build_id' => '9230b8e9',
    'container.build_time' => 1720948905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOv1aVJ');
