<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBTqCwB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBTqCwB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKBTqCwB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKBTqCwB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKBTqCwB\App_KernelDevDebugContainer([
    'container.build_hash' => 'KBTqCwB',
    'container.build_id' => '6af562e7',
    'container.build_time' => 1720873823,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBTqCwB');
