<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'register_form' => [[], ['_controller' => 'App\\Controller\\UserController::registerForm'], [], [['text', '/register_form']], [], [], []],
    'register_user' => [[], ['_controller' => 'App\\Controller\\UserController::registerUser'], [], [['text', '/register_user']], [], [], []],
    'login_form' => [[], ['_controller' => 'App\\Controller\\UserController::logInForm'], [], [['text', '/login_form']], [], [], []],
    'login_user' => [[], ['_controller' => 'App\\Controller\\UserController::logInUser'], [], [['text', '/login_user']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/logout']], [], [], []],
    'find_username' => [[], ['_controller' => 'App\\Controller\\UserController::findUsername'], [], [['text', '/find_username']], [], [], []],
    'start_lobby_page' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::startLobbyPage'], [], [['text', '/start_lobby_page']], [], [], []],
    'create_lobby' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::createLobby'], [], [['text', '/create_lobby']], [], [], []],
    'join_lobby' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::joinLobby'], [], [['text', '/join_lobby']], [], [], []],
    'find_key_room' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::findKeyRoom'], [], [['text', '/find_key_room']], [], [], []],
    'lobby_page' => [['keyRoom'], ['_controller' => 'App\\Controller\\LobbyPlaceController::lobbyPage'], [], [['variable', '/', '[^/]++', 'keyRoom', true], ['text', '/lobby_page']], [], [], []],
    'quit_lobby' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::quitFromLooby'], [], [['text', '/quit_lobby']], [], [], []],
    'kick_from_lobby' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::kickFromLobby'], [], [['text', '/kick_from_lobby']], [], [], []],
    'make_player_ready' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::makePlayerReady'], [], [['text', '/make_player_ready']], [], [], []],
    'make_player_not_ready' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::makePlayerNotReady'], [], [['text', '/make_player_not_ready']], [], [], []],
    'get_player_status' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::getPlayerStatus'], [], [['text', '/get_player_status']], [], [], []],
    'find_count_players' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::findCountPLayersInLobby'], [], [['text', '/find_count_players']], [], [], []],
    'is_all_players_ready' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::isAllPlayersReady'], [], [['text', '/is_all_players_ready']], [], [], []],
    'get_ids_players' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::getPlayersIdsInLobby'], [], [['text', '/get_player_ids']], [], [], []],
    'make_players_not_ready' => [[], ['_controller' => 'App\\Controller\\LobbyPlaceController::makePlayersNotReady'], [], [['text', '/make_players_not_ready']], [], [], []],
    'main_game' => [['keyRoom'], ['_controller' => 'App\\Controller\\GameController::mainGame'], [], [['variable', '/', '[^/]++', 'keyRoom', true], ['text', '/main_game']], [], [], []],
    'start_game' => [[], ['_controller' => 'App\\Controller\\GameController::startGame'], [], [['text', '/start_game']], [], [], []],
    'create_map' => [[], ['_controller' => 'App\\Controller\\GameController::createGameMap'], [], [['text', '/create_map']], [], [], []],
    'find_map' => [[], ['_controller' => 'App\\Controller\\GameController::findGameMap'], [], [['text', '/find_map']], [], [], []],
    'update_map' => [[], ['_controller' => 'App\\Controller\\GameController::updateGameMap'], [], [['text', '/update_map']], [], [], []],
    'end_game' => [[], ['_controller' => 'App\\Controller\\GameController::endGame'], [], [['text', '/end_game']], [], [], []],
    'error_page' => [['messageCode'], ['_controller' => 'App\\Controller\\ErrorController::onError'], [], [['variable', '/', '[^/]++', 'messageCode', true], ['text', '/error_page']], [], [], []],
];
